nome = str(input('Digite seu nome completo: ')).strip().title()
nome = nome.split()
print('Prazer em conhece-lo!')
print(f'Seu primeiro nome é {nome[0]}')
print(f'Seu ultimo nome é {nome[(len(nome) - 1)]}')
